### ISSUE TITLE
wrong reward calculation (and incorrect state) during sync when there are invalid blocks

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1763]
See screenshots:

1. correct behaviour: there are 53 blocks in layer 20, but one of them is contextually invalid (as shown after the Tortoise finishes with layer 22, and pbase becomes 21). Then we calculate rewards given there 52 blocks.

<img width="1165" alt="Screen Shot 2020-01-30 at 7 00 09 PM" src="https://user-images.githubusercontent.com/35497694/73473480-88a62780-4395-11ea-8bb3-a82bc64bbded.png">

2. incorrect behaviour: miners sync layer 20, and after running the tortoise they also know that one block is contextually invalid. Nevertheless, calculation of reward takes into account 53 blocks, hence we also get a different state

<img width="1147" alt="Screen Shot 2020-01-30 at 6 59 48 PM" src="https://user-images.githubusercontent.com/35497694/73474137-9f994980-4396-11ea-884d-ab1f366d3162.png">

**Comment by barakshani** [comment]
Looks like it happens with one of the very recent (last day or two) changes to develop - with a branch from a couple of days ago, new syncing miners are behaving fine.

Moreover, we see that (with the new branch) syncing miners do not print the "new state root" log during epoch 0, and that the "end of layer state root" prints 0000000000000000 (during epoch 0)

**Comment by barakshani** [comment]
Another issue regarding the branches (see screenshots):
In layer 437 both miners (one with the old branch, one with the new) have the same state. There are 42 blocks in layer 438, and one of these blocks has no AssATX, so we skip reward for this block.

1. Old branch: we see `skipping reward distribution for block with no ATX`, but then under `Reward calculated` it says that the number of blocks is 42.
<img width="1213" alt="Screen Shot 2020-02-01 at 12 44 21 PM" src="https://user-images.githubusercontent.com/35497694/73590922-fdda3f80-44f0-11ea-827c-1eb637a0f01d.png">

2. New branch: we also see `skipping reward distribution for block with no ATX`, and indeed under `Reward calculated` it says that the number of blocks is 41.
<img width="1216" alt="Screen Shot 2020-02-01 at 12 49 47 PM" src="https://user-images.githubusercontent.com/35497694/73590946-59a4c880-44f1-11ea-8925-094b17c57739.png">

Hence, the miners end with different state.

**Comment by noamnelke** [comment]
This was fixed by @almogdepaz in #1741:

https://github.com/spacemeshos/go-spacemesh/pull/1741/files#diff-4b8a85baa8491a575dcd84dbdf79aff4L546-R555

@barakshani please confirm we can close this issue.

**Comment by barakshani** [comment]
The last (third) comment is indeed this fix, but the first two are not fixed - it is something new; it is probably when we started getting the problem in https://github.com/spacemeshos/go-spacemesh/pull/1762

Generally, it is not clear to me why "new state root" and "new layer hash" behave differently (one works fine across all nodes, the other not). And as a side note, "new layer hash" should not be updated only when p_base advances - the two are unrelated.

**Comment by noamnelke** [comment]
> Moreover, we see that (with the new branch) syncing miners do not print the "new state root" log during epoch 0, and that the "end of layer state root" prints 0000000000000000 (during epoch 0)

This should be fixed by #1744.

You're third commend is exactly like the original issue, and IMO it's because your "old branch" is before #1741 (bad) and your "new branch" is after. If I'm wrong about this - please lmk which branches you're running.

**Comment by noamnelke** [comment]
I just realized you said "during epoch 0". During layers 0 and 1 I actually can't explain why we ever had a non-zero state root (but we did when I merged #1744). I'm still investigating this.

**Comment by barakshani** [comment]
If you run Develop now you get the bugs from my first (issue description) and second comments

**Comment by noamnelke** [comment]
@barakshani @antonlerner 

So... is anything here still relevant? I think #1780 fixes the last relevant issue here, right?

**Comment by barakshani** [comment]
I referenced to original issue here to 2 opened issues (above). We need tests for that scenario.. For your question, yes it seems so, but need to test it.

**Comment by barakshani** [comment]
@noamnelke regarding point 2, now we just see `end of layer state root` at the first epoch but not the `new state root`. Recall that it is in the first epoch because we don't do txs, and since there is no block rewards yet, the state does not update.
Just to clarify that we don't see 0x00000 anymore. The miner starts with:
`started processor with state root 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421`
